print("                            GLOBAL THERMONUCLEAR WAR\n\n")
print("      ___    ____             ____                   _______________")
print("     |   \\__/    \\_____      /    |              ___/               \\")
print("     |                 \\    /    /           ___/                    \\______")
print("     |                  \\__/    /           /                               \\")
print("     |                           \\        _/                                 |")
print("     |        UNITED STATES       |      /           SOVIET UNION       ____/")
print("      \\                           /     /                          ____/")
print("        \\                        /     |                          /")
print("          \\________          __/       \\          _____   /\\_    /")
print("                   \\__      /            \\__    _/     \\_/   \\__/")
print("                      \\____/                \\__/")
print("\n");
print("WHICH SIDE DO YOU WANT?\n\n")
print("  1. UNITED STATES\n")
print("  2. SOVIET UNION\n\n")
#side = int(input("PLEASE CHOOSE ONE: "))